### ISSUE TITLE
Переделать state_ctx в StateMachine

### ISSUE THREAD

**Issue by aedobrynin** [getboard/whiteboard#26]
Сейчас это словарь. Лучше сделать это просто ссылкой на объект, а стейт сам его заполнит чем надо.
Грубо говоря, изначально `state_ctx = None`. При первом входе в `handle_event` для стейта делать что-то типа:
```
if state_ctx is None:
  state_ctx = EditTextStateContext()
```
, где
```
@dataclass
CreateTextStateContext:
   text_id: int
   foo: bool
   bar: str
```
Это поможет более структурировать контекст состояния
